# Generated by Django 5.0.7 on 2024-09-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="description",
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="status",
            field=models.CharField(
                choices=[("ON", "ongoing"), ("PA", "past")],
                default="PA",
                max_length=100,
            ),
        ),
    ]
