# Generated by Django 5.0.7 on 2024-09-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_projectmodel_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="description",
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="status",
            field=models.CharField(
                choices=[("ON", "ongoing"), ("PA", "past")], max_length=100
            ),
        ),
    ]
