# Generated by Django 5.0.7 on 2024-09-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projectmodel_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="status",
            field=models.CharField(
                choices=[("ON", "ongoing"), ("PA", "past")], default="PA", max_length=2
            ),
        ),
    ]
