# Generated by Django 5.0.7 on 2024-08-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alt_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='srn',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
