# Generated by Django 5.0.7 on 2024-08-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_srn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alt_email',
        ),
    ]
